### ISSUE TITLE
Incorrect if statement

### ISSUE THREAD

**Issue by Seniatical** [Pastlecry/Lemonade-Tool#1]
https://github.com/Pastlecry/Lemonade-Tool/blob/6b8918765516f881c118e62db9b0530a726a6c31/dos.py#L74

Should be `if protocol.lower() == "tcp"` or if you wish to stick to the current format `if protocol == "TCP" or protocol == "tcp"`.
Issue currently is that it will be "TCP" after evaluating the statement which makes the user input statement useless

**Comment by Pastlecry** [comment]
Fixed thank you! :3
